# Translation of Odoo Server.
# This file contains the translation of the following modules:
# * payment_xendit
#
# Translators:
# Wil Odoo, 2024
# Junko Augias, 2024
#
# "Junko Augias (juau)" <juau@odoo.com>, 2025.
msgid ""
msgstr ""
"Project-Id-Version: Odoo Server 17.0\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2024-01-29 10:46+0000\n"
"PO-Revision-Date: 2025-10-28 08:05+0000\n"
"Last-Translator: \"Junko Augias (juau)\" <juau@odoo.com>\n"
"Language-Team: Japanese <https://translate.odoo.com/projects/odoo-17/"
"payment_xendit/ja/>\n"
"Language: ja\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: \n"
"Plural-Forms: nplurals=1; plural=0;\n"
"X-Generator: Weblate 5.12.2\n"

#. module: payment_xendit
#. odoo-python
#: code:addons/payment_xendit/models/payment_transaction.py:0
#, python-format
msgid ""
"An error occurred during the processing of your payment (status %s). Please "
"try again."
msgstr "支払処理中にエラーが発生しました(ステータス %s) 。再度試して下さい。"

#. module: payment_xendit
#: model:ir.model.fields,field_description:payment_xendit.field_payment_provider__code
msgid "Code"
msgstr "コード"

#. module: payment_xendit
#. odoo-python
#: code:addons/payment_xendit/models/payment_provider.py:0
#, python-format
msgid "Could not establish the connection to the API."
msgstr "APIへの接続を確立できませんでした。"

#. module: payment_xendit
#. odoo-python
#: code:addons/payment_xendit/models/payment_transaction.py:0
#, python-format
msgid "No transaction found matching reference %s."
msgstr "参照に一致する取引が見つかりません%s。"

#. module: payment_xendit
#: model:ir.model,name:payment_xendit.model_payment_provider
msgid "Payment Provider"
msgstr "決済プロバイダー"

#. module: payment_xendit
#: model:ir.model,name:payment_xendit.model_payment_transaction
msgid "Payment Transaction"
msgstr "支払取引"

#. module: payment_xendit
#. odoo-python
#: code:addons/payment_xendit/models/payment_transaction.py:0
#, python-format
msgid "Received data with missing reference."
msgstr "参照が欠落しているデータを受信しました。"

#. module: payment_xendit
#: model_terms:ir.ui.view,arch_db:payment_xendit.payment_provider_form_xendit
msgid "Secret Key"
msgstr "シークレットキー"

#. module: payment_xendit
#. odoo-python
#: code:addons/payment_xendit/models/payment_provider.py:0
#, python-format
msgid ""
"The communication with the API failed. Xendit gave us the following "
"information: '%s'"
msgstr "APIとの通信に失敗しました。Xenditから以下の情報が得られました: '%s'"

#. module: payment_xendit
#: model:ir.model.fields,help:payment_xendit.field_payment_provider__code
msgid "The technical code of this payment provider."
msgstr "この決済プロバイダーのテクニカルコード。"

#. module: payment_xendit
#: model_terms:ir.ui.view,arch_db:payment_xendit.payment_provider_form_xendit
msgid "Webhook Token"
msgstr "Webhookトークン"

#. module: payment_xendit
#: model:ir.model.fields.selection,name:payment_xendit.selection__payment_provider__code__xendit
msgid "Xendit"
msgstr "Xendit"

#. module: payment_xendit
#: model:ir.model.fields,field_description:payment_xendit.field_payment_provider__xendit_secret_key
msgid "Xendit Secret Key"
msgstr "Xenditシークレットキー"

#. module: payment_xendit
#: model:ir.model.fields,field_description:payment_xendit.field_payment_provider__xendit_webhook_token
msgid "Xendit Webhook Token"
msgstr "Xendit Webhookトークン"
